targets:
  - id: "159934"
    source: "etf_com_cn"
    name: "黄金ETF易方达"
  - id: "159941"
    source: "etf_com_cn"
    name: "纳指ETF广发"
  - id: "159259"
    source: "etf_com_cn"
    name: "成长ETF易方达"
  - id: "159263"
    source: "etf_com_cn"
    name: "价值ETF易方达"
  - id: "511130"
    source: "etf_com_cn"
    name: "30年国债ETF博时"
  - id: "cb_equal_weight"
    source: "jisilu_cb_index"
    name: "集思录转债等权"
