targets:
  - id: "159934"
    source: "etf_com_cn"
    name: "黄金ETF易方达"
  - id: "159941"
    source: "etf_com_cn"
    name: "纳指ETF广发"
  - id: "159259"
    source: "etf_com_cn"
    name: "标普ETF景顺"
  - id: "159263"
    source: "etf_com_cn"
    name: "德国ETF"
  - id: "511130"
    source: "etf_com_cn"
    name: "10年地方债ETF"
  - id: "511380"
    source: "etf_com_cn"
    name: "可转债ETF"
  - id: "cb_equal_weight"
    source: "jisilu_cb_index"
    name: "集思录转债等权"
